[package]
name = "acs-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[[bin]]
name = "acs-gui"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
acs-core = { path = "../crates/core" }
tauri = { version = "2", features = [] }
serde.workspace = true
serde_json.workspace = true
